language: python
python:
    - 3.4
    - 3.5

install:
    - pip install -r requirements.txt
    - pip install coveralls
script:
    - cd ./homes
    - python manage.py test
    - coverage run --source=api manage.py test
after_success:
    - coveralls
