# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-10 10:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_timestamp', models.DateTimeField(auto_now=True)),
                ('listing_timestamp', models.DateTimeField()),
                ('listing_type', models.CharField(choices=[('F', 'For Sale'), ('S', 'Sold')], max_length=1)),
                ('price', models.FloatField()),
                ('bedrooms', models.FloatField(blank=True, null=True)),
                ('bathrooms', models.FloatField(blank=True, null=True)),
                ('car_spaces', models.FloatField(blank=True, null=True)),
                ('building_size', models.FloatField(blank=True, null=True)),
                ('land_size', models.FloatField(blank=True, null=True)),
                ('size_units', models.CharField(choices=[('M', 'metric'), ('I', 'imperial')], max_length=1)),
                ('raw_address', models.CharField(max_length=512)),
                ('geocoded_address', models.CharField(max_length=512)),
            ],
        ),
    ]
