# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-18 00:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20160417_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='valid',
            field=models.BooleanField(default=True),
        ),
    ]
