# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-04 00:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20160418_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='listing_type',
            field=models.CharField(choices=[('F', 'For Sale'), ('S', 'Sold'), ('A', 'Appraised')], max_length=1),
        ),
    ]
