# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-16 04:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20160511_0148'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='confirmation_code',
            field=models.CharField(default='', max_length=512),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='confirmation_date',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 5, 16, 4, 38, 59, 334254, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
