# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-21 11:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20160516_0438'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw', models.CharField(max_length=2048)),
                ('subpremise', models.IntegerField(blank=True, null=True)),
                ('street_number', models.IntegerField()),
                ('route', models.CharField(max_length=512)),
                ('locality', models.CharField(max_length=512)),
                ('area_level_2', models.CharField(max_length=512)),
                ('area_level_1', models.CharField(max_length=512)),
                ('country', models.CharField(max_length=128)),
                ('postal_code', models.CharField(max_length=50)),
                ('formatted_address', models.CharField(max_length=1000)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='property',
            name='geocoded_address',
        ),
        migrations.AddField(
            model_name='property',
            name='address_object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Address'),
        ),
    ]
