# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-22 07:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20160621_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='formatted_address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='address',
            name='raw',
            field=models.TextField(),
        ),
    ]
